run:
  timeout: 2m

linters:
  enable:
    - govet
    - errcheck
    - deadcode
    - unused
    - gofmt
    - gocritic
    - revive

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0
