
title: Flutter Build Patrol
summary: Install and Build Patrol for Flutter Projects
description: |-
  This steps initialy does:
  - Installing the Patrol CLI if it is not already installed.
  - Validates the installed Patrol CLI version and your project's Patrol version.
  - Builds the Patrol APK, iOS or BOTH if specified.
website: https://github.com/gpac-Tech-Hub/patrol_build_flutter
source_code_url: https://github.com/gpac-Tech-Hub/patrol_build_flutter
support_url: https://github.com/gpac-Tech-Hub/patrol_build_flutter/issues

project_type_tags:
- flutter


type_tags:
  - test
  - build
  - integration


toolkit:
  go:
    package_name: github.com/gpac-Tech-Hub/patrol_build_flutter

inputs:
- patrol_version: $FLUTTER_BUILD_PATROL_VERSION
  opts:
    title: Custom Patrol Version
    summary: Custom Patrol Version
    description: |-
      If you want to use a specific version of Patrol, you can specify it here.
      If you leave this input empty, the step will use the latest version of Patrol.
      This is useful if you want to test a specific version of Patrol or if you have a specific version that you need to use for your project.
      You can specify the version in the format `X.Y.Z`, for example `1.2.3`.
      If you specify a version that is not available, the step will fail.
    is_required: false
- platform: $FLUTTER_BUILD_PATROL_PLATFORM
  opts:
    title: Platform
    summary: The selected platform will be built, or both iOS and Android if you select both
    description: The selected platform will be built, or both iOs and Android if you select both
    is_required: true
    value_options:
    - both
    - ios
    - android
- target: $FLUTTER_BUILD_PATROL_TARGET
  opts:
    title: Target
    summary: The selected target will be built.
    description: |-
      The selected target will be built.
      Need to select your patrol integration test file.
      This file path should be given.
    is_required: true
    value_options:
    - both
    - ios
    - android
- build_type: $FLUTTER_BUILD_PATROL_BUILD_TYPE
  opts:
    title: Build Type
    summary: The build type to use for the selected Platform
    description: |-
      The build type to use for the selected Platform.
      If you leave this input empty, the step will use the default build type, which is `release`.
      You can specify `debug` or `release` as the build type.
    is_required: false
    value_options:
    - debug
    - release
- tags: $FLUTTER_BUILD_PATROL_TAGS
  opts:
    title: Tags
    summary: Tags to filter the tests to run
    description: |-
      Tags to filter the tests to run.
      You can specify multiple tags separated by commas.
      If you leave this input empty, all tests will be run.
    is_required: false
- excluded_tags: $FLUTTER_BUILD_PATROL_EXCLUDED_TAGS
  opts:
    title: Excluded Tags
    summary: Tags to exclude from the tests to run
    description: |-
      Tags to exclude from the tests to run.
      You can specify multiple tags separated by commas.
      If you leave this input empty, no tags will be excluded.
    is_required: false
- is_verbose: $FLUTTER_BUILD_PATROL_IS_VERBOSE
  opts:
    title: Verbose
    summary: Enable verbose output
    description: |-
      If you want to enable verbose output for the step, you can set this input to `true`.
      If you leave this input empty, the step will not enable verbose output.
      Verbose output can help you debug issues with the step.
      It will print additional information about the step's execution.
    is_required: false
    value_options:
    - true
    - false
- is_covered: $FLUTTER_BUILD_PATROL_IS_COVERED
  opts:
    title: Is Covered
    summary: Enable coverage for the tests
    description: |-
      If you want to enable coverage for the tests, you can set this input to `true`.
      If you leave this input empty, the step will not enable coverage.
    is_required: false
    value_options:
    - true
    - false

outputs:
  - PATROL_APK_PATH:
    opts:
      title: Patrol APK Path
      summary: This output contains the path to the Patrol APK file
      description: The path to the Patrol APK file generated by the step
  - IOS_APP_PATH:
    opts:
      title: Patrol iOS App Path
      summary: This output contains the path to the Patrol iOS app file
      description: The path to the Patrol iOS app file generated by the step
  - TEST_COVERAGE_ICOV_PATH:
    opts:
      title: Test Coverage Icov Path
      summary: This output contains the path to the test coverage file
      description: The path to the test coverage file generated by the step
