
title: Flutter Build Patrol
summary: Install and Build Patrol for Flutter Projects
description: |-
  This steps initialy does:
  - Installing the Patrol CLI if it is not already installed.
  - Validates the installed Patrol CLI version and your project's Patrol version.
  - Builds the Patrol APK, iOS or BOTH if specified.
website: https://github.com/gpac-Tech-Hub/patrol_build_flutter
source_code_url: https://github.com/gpac-Tech-Hub/patrol_build_flutter
support_url: https://github.com/gpac-Tech-Hub/patrol_build_flutter/issues

project_type_tags:
- flutter


type_tags:
  - test
  - build
  - integration


toolkit:
  go:
    package_name: github.com/gpac-Tech-Hub/patrol_build_flutter

inputs:
- platform: both
  opts:
    title: Platform
    summary: The selected platform will be built, or both iOS and Android if you select both
    description: The selected platform will be built, or both iOs and Android if you select both
    is_required: true
    value_options:
    - both
    - ios
    - android
- patrol_version: ""
  opts:
    title: Custom Patrol Version
    summary: Custom Patrol Version
    description: |-
      If you want to use a specific version of Patrol, you can specify it here.
      If you leave this input empty, the step will use the latest version of Patrol.
      If you specify a version, it will check if that version is installed,
      and if not, it will install it.
      
      Please note that the version you specify must be compatible with your project.
    is_required: false

outputs:
  - PATROL_APK_PATH:
    opts:
      title: Patrol APK Path
      summary: This output contains the path to the Patrol APK file
      description: The path to the Patrol APK file generated by the step
  - IOS_APP_PATH:
    opts:
      title: Patrol iOS App Path
      summary: This output contains the path to the Patrol iOS app file
      description: The path to the Patrol iOS app file generated by the step
