# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Release Binary

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0

permissions:
  contents: write # Required to upload binaries to GitHub Releases

jobs:
  # First job: Call the reusable workflow to generate a tag
  tag:
    uses: ./.github/workflows/bitrise_tag.yaml

  # Second job: Build and release, using the tag from the first job
  build_and_release:
    runs-on: ubuntu-latest
    # This job must wait for the 'tag' job to complete
    needs: tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Build Binaries 🛠️
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/patrol-binary-linux
          GOOS=darwin GOARCH=amd64 go build -o dist/patrol-binary-darwin
          GOOS=windows GOARCH=amd64 go build -o dist/patrol-binary-windows.exe

      - name: Create GitHub Release and Tag 🚀
        uses: softprops/action-gh-release@v2
        with:
          # Use the output from the 'tag' job
          tag_name: ${{ needs.tag.outputs.tag }}
          files: |
            dist/*
