name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Vet
      run: go vet ./...

    - name: Validate Bitrise step.yml
      run: |
        curl -sL https://github.com/bitrise-io/stepman/releases/latest/download/stepman-linux-x86_64 -o stepman
        chmod +x stepman
        ./stepman audit --step-yml ./step.yml
